/// Build and parse .ustx documents for the editor.
///
/// * [buildUstx] serializes every track (name + notes + drawn pitch curves)
///   into a .ustx document the engine renders. Format mirrors
///   native/tools/synth-cli/tests/data/demo-song.ustx. Pitch points are
///   written as ustx pitch data (x in ms from note start, y in 0.1
///   semitones) so the engine's PitchComputer actually bends the f0.
/// * [parseUstx] reads a .ustx document back into editable tracks (the
///   "Open project" path). Line-based YAML subset — enough for Lilt/OpenUtau
///   documents with plain `notes: [...]` blocks.
library;

import 'models.dart';

/// Beats → ticks at 480 ticks/beat (quarter note = 480 ticks).
int beatsToTicks(double beats) => (beats * 480).round();

/// Ticks → beats.
double ticksToBeats(int ticks) => ticks / 480;

/// ms per beat at [bpm] (used to convert curve beat offsets to ustx ms).
double msPerBeat(int bpm) => 60000 / bpm;

/// One serializable track: name + notes (curves are passed separately —
/// the editor keeps one curve list per track).
class TrackNotes {
  const TrackNotes({required this.name, required this.notes});
  final String name;
  final List<Note> notes;
}

/// Serialize the editor's tracks into a .ustx document.
///
/// [tracks] is ordered (track index = order). [curvesByTrack] maps track
/// index → drawn pitch points (beat, semitones); only points inside a
/// note's range are attached to that note.
String buildUstx({
  required String name,
  required List<TrackNotes> tracks,
  Map<int, List<PitchPoint>> curvesByTrack = const {},
  int bpm = 120,
}) {
  final buf = StringBuffer()
    ..writeln('# Generated by Lilt editor')
    ..writeln('ustx_version: 0.9')
    ..writeln('name: $name')
    ..writeln("comment: ''")
    ..writeln("output_dir: ''")
    ..writeln("cache_dir: ''")
    ..writeln('bpm: $bpm')
    ..writeln('beat_per_bar: 4')
    ..writeln('beat_unit: 4')
    ..writeln('resolution: 1')
    ..writeln('expressions: {}')
    ..writeln('time_signatures:')
    ..writeln('- bar_position: 0')
    ..writeln('  beat_per_bar: 4')
    ..writeln('  beat_unit: 4')
    ..writeln('tempos:')
    ..writeln('- position: 0')
    ..writeln('  bpm: $bpm')
    ..writeln('tracks:');
  for (var i = 0; i < tracks.length; i++) {
    final t = tracks[i];
    buf
      ..writeln('- track_name: ${t.name}')
      ..writeln('  solo: false')
      ..writeln('  mute: false')
      ..writeln('  volume: 0')
      ..writeln('  pan: 0')
      ..writeln("  singer: ''")
      ..writeln("  phonemizer: 'English'")
      ..writeln('  voice_parts: []')
      ..writeln('  wave_parts: []')
      ..writeln('  track_expressions: []')
      ..writeln('  track_curves: []');
  }
  buf.writeln('voice_parts:');
  for (var i = 0; i < tracks.length; i++) {
    final t = tracks[i];
    final curves = curvesByTrack[i] ?? const <PitchPoint>[];
    final mpb = msPerBeat(bpm);
    buf
      ..writeln('- name: Part${i + 1}')
      ..writeln("  comment: ''")
      ..writeln('  track_no: $i')
      ..writeln('  position: 0')
      ..writeln('  notes:');
    for (final n in t.notes) {
      buf
        ..writeln('  - position: ${beatsToTicks(n.position)}')
        ..writeln('    duration: ${beatsToTicks(n.duration)}')
        ..writeln('    tone: ${60 + n.pitch}') // Note.pitch is semitones from C4
        ..writeln('    lyric: ${n.lyric}')
        ..writeln('    pitch:')
        ..writeln('      data:')
        ..writeln('      - x: -1')
        ..writeln('        y: 0')
        ..writeln('        shape: io');
      for (final p in curves) {
        if (p.beat < n.position || p.beat > n.position + n.duration) {
          continue;
        }
        final xMs = ((p.beat - n.position) * mpb).round();
        final y = (p.semitones * 10).round();
        buf
          ..writeln('      - x: $xMs')
          ..writeln('        y: $y')
          ..writeln('        shape: io');
      }
      buf
        ..writeln('      - x: 1')
        ..writeln('        y: 0')
        ..writeln('        shape: io')
        ..writeln('      snap_first: true')
        ..writeln('    vibrato: {length: 0, period: 175, depth: 25, in: 10, out: 10, shift: 0, drift: 0}');
    }
    buf.writeln('  curves: []');
  }
  buf.writeln('wave_parts: []');
  return buf.toString();
}

/// Parse a .ustx document into editable tracks (name + notes).
///
/// Handles the YAML subset Lilt writes plus the OpenUtau shape: `tracks:`
/// list (track_name), `voice_parts:` list (track_no + notes:). Notes carry
/// position/duration (ticks), tone (MIDI) and lyric. Unknown keys are
/// ignored. Returns an empty list when no voice parts are found.
List<TrackNotes> parseUstx(String yaml) {
  final tracks = <TrackNotes>[];
  final trackNames = <int, String>{}; // index → name (from tracks: block)
  final parts = <_Part>[];

  var inTracks = false;
  var inParts = false;
  var inNotes = false;
  var trackIdx = 0;
  _Part? currentPart;
  _RawNote? currentNote;

  for (final raw in yaml.split('\n')) {
    final line = raw.trimRight();
    if (line.trim().isEmpty || line.trim().startsWith('#')) continue;

    // Section transitions by top-level key.
    if (!line.startsWith(' ') && !line.startsWith('-')) {
      inTracks = line == 'tracks:';
      inParts = line == 'voice_parts:';
      if (line != 'notes:' && !line.startsWith('tracks:') &&
          !line.startsWith('voice_parts:')) {
        inNotes = false;
      }
      continue;
    }

    if (inTracks && line.trim().contains('track_name:')) {
      trackNames[trackIdx] = _scalar(line);
      trackIdx += 1;
      continue;
    }
    if (inTracks && line.startsWith('- ')) {
      trackIdx = trackNames.length;
      continue;
    }

    if (inParts) {
      if (line.startsWith('- name:')) {
        currentPart = _Part();
        parts.add(currentPart);
        continue;
      }
      if (line.trim().startsWith('track_no:')) {
        currentPart?.trackNo = int.tryParse(_scalar(line)) ?? 0;
        continue;
      }
      if (line.trim() == 'notes:') {
        inNotes = true;
        continue;
      }
      if (inNotes) {
        if (line.startsWith('  - position:')) {
          currentNote = _RawNote()
            ..position = int.tryParse(_scalar(line)) ?? 0;
          currentPart?.notes.add(currentNote);
          continue;
        }
        final n = currentNote;
        if (n == null) continue;
        if (line.trim().startsWith('duration:')) {
          n.duration = int.tryParse(_scalar(line)) ?? 0;
        } else if (line.trim().startsWith('tone:')) {
          n.tone = int.tryParse(_scalar(line)) ?? 60;
        } else if (line.trim().startsWith('lyric:')) {
          n.lyric = _scalar(line);
        }
      }
    }
  }

  for (final p in parts) {
    final name = trackNames[p.trackNo] ?? 'Track ${p.trackNo + 1}';
    tracks.add(TrackNotes(
      name: name,
      notes: [
        for (final n in p.notes)
          Note(
            lyric: n.lyric,
            pitch: n.tone - 60, // MIDI → semitones from C4
            position: ticksToBeats(n.position),
            duration: ticksToBeats(n.duration),
          ),
      ],
    ));
  }
  return tracks;
}

/// Scalar value of `key: value` (strips quotes).
String _scalar(String line) {
  final idx = line.indexOf(':');
  if (idx < 0) return '';
  var v = line.substring(idx + 1).trim();
  if (v.length >= 2 &&
      ((v.startsWith("'") && v.endsWith("'")) ||
          (v.startsWith('"') && v.endsWith('"')))) {
    v = v.substring(1, v.length - 1);
  }
  return v;
}

class _Part {
  int trackNo = 0;
  final notes = <_RawNote>[];
}

class _RawNote {
  int position = 0;
  int duration = 0;
  int tone = 60;
  String lyric = '';
}
